-- ============================================================
--  CHAINGUARD: Digital Evidence Chain of Custody Management System
--  Course: UCS310 - Database Management Systems | B.Tech 2nd Year
--  Academic Year: 2025-26
--  Environment: Oracle Live SQL / FreeSQL
-- ============================================================

SET SERVEROUTPUT ON SIZE UNLIMITED;

-- ============================================================
-- CLEANUP: Drop all objects so script is safely re-runnable
-- ============================================================

BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE pkg_chainguard_reports';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION fn_validate_chain_integrity'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE sp_custody_transfer';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE pkg_bypass';                   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_evidence_audit';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_tamper_lock';              EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_auto_first_custody';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_court_schedule';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_lab_pending';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_custody_chain';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_active_cases';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Audit_Log          CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Court_Requisitions CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Lab_Analysis       CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Custody_Transfers  CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Evidence           CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Cases              CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Storage_Facilities CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Forensic_Labs      CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Officers           CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ============================================================
-- SECTION 1: DDL — CREATE TABLES AND INDEXES
-- ============================================================

-- 1. Officers
CREATE TABLE Officers (
    Officer_ID          NUMBER(6)       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name                VARCHAR2(100)   NOT NULL,
    Badge_Number        VARCHAR2(20)    NOT NULL UNIQUE,
    Rank                VARCHAR2(50)    NOT NULL,
    Department          VARCHAR2(100)   NOT NULL,
    Authorization_Level VARCHAR2(20)    NOT NULL
        CHECK (Authorization_Level IN ('OFFICER','ANALYST','SUPERVISOR','ADMIN')),
    Phone               VARCHAR2(15),
    Email               VARCHAR2(100)
);

-- 2. Forensic_Labs
CREATE TABLE Forensic_Labs (
    Lab_ID          NUMBER(6)       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Lab_Name        VARCHAR2(100)   NOT NULL,
    Location        VARCHAR2(150)   NOT NULL,
    Specialization  VARCHAR2(100),
    Contact_Phone   VARCHAR2(15)
);

-- 3. Storage_Facilities
CREATE TABLE Storage_Facilities (
    Facility_ID     NUMBER(6)       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Facility_Name   VARCHAR2(100)   NOT NULL,
    Location        VARCHAR2(150)   NOT NULL,
    Capacity        NUMBER(6)       NOT NULL CHECK (Capacity > 0),
    Facility_Type   VARCHAR2(20)    NOT NULL
        CHECK (Facility_Type IN ('COLD_STORAGE','SECURE_VAULT','EVIDENCE_ROOM','DIGITAL_VAULT'))
);

-- 4. Cases (FK -> Officers)
CREATE TABLE Cases (
    Case_ID                  NUMBER(6)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FIR_Number               VARCHAR2(30) NOT NULL UNIQUE,
    Crime_Type               VARCHAR2(100) NOT NULL,
    Date_Reported            DATE          NOT NULL,
    Status                   VARCHAR2(25)  NOT NULL DEFAULT 'OPEN'
        CHECK (Status IN ('OPEN','CLOSED','UNDER_INVESTIGATION','ARCHIVED')),
    Investigating_Officer_ID NUMBER(6)     NOT NULL,
    Description              VARCHAR2(500),
    CONSTRAINT fk_case_officer FOREIGN KEY (Investigating_Officer_ID)
        REFERENCES Officers(Officer_ID)
);

-- 5. Evidence (FK -> Cases, Officers, Storage_Facilities)
CREATE TABLE Evidence (
    Evidence_ID          NUMBER(6)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Case_ID              NUMBER(6)    NOT NULL,
    Description          VARCHAR2(300) NOT NULL,
    Category             VARCHAR2(20)  NOT NULL
        CHECK (Category IN ('WEAPON','BIOLOGICAL','ELECTRONIC','DOCUMENT','NARCOTIC','OTHER')),
    Condition            VARCHAR2(20)  NOT NULL DEFAULT 'INTACT'
        CHECK (Condition IN ('INTACT','DAMAGED','DEGRADED','CONTAMINATED')),
    Date_Collected       DATE          NOT NULL,
    Current_Location     VARCHAR2(150) NOT NULL,
    Current_Custodian_ID NUMBER(6)     NOT NULL,
    Facility_ID          NUMBER(6),
    Tamper_Seal          VARCHAR2(50)  NOT NULL UNIQUE,
    CONSTRAINT fk_ev_case     FOREIGN KEY (Case_ID)              REFERENCES Cases(Case_ID),
    CONSTRAINT fk_ev_officer  FOREIGN KEY (Current_Custodian_ID) REFERENCES Officers(Officer_ID),
    CONSTRAINT fk_ev_facility FOREIGN KEY (Facility_ID)          REFERENCES Storage_Facilities(Facility_ID)
);

-- 6. Custody_Transfers (FK -> Evidence, Officers x2)
CREATE TABLE Custody_Transfers (
    Transfer_ID        NUMBER(8)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Evidence_ID        NUMBER(6)    NOT NULL,
    From_Officer_ID    NUMBER(6)    NOT NULL,
    To_Officer_ID      NUMBER(6)    NOT NULL,
    Transfer_Date      DATE         NOT NULL DEFAULT SYSDATE,
    Location           VARCHAR2(150) NOT NULL,
    Reason             VARCHAR2(200) NOT NULL,
    Evidence_Condition VARCHAR2(20)  NOT NULL
        CHECK (Evidence_Condition IN ('INTACT','DAMAGED','DEGRADED','CONTAMINATED')),
    Status             VARCHAR2(15)  NOT NULL DEFAULT 'PENDING'
        CHECK (Status IN ('PENDING','COMPLETED','CANCELLED')),
    Is_Sealed          CHAR(1)       NOT NULL DEFAULT 'N'
        CHECK (Is_Sealed IN ('Y','N')),
    CONSTRAINT fk_ct_evidence FOREIGN KEY (Evidence_ID)     REFERENCES Evidence(Evidence_ID),
    CONSTRAINT fk_ct_from_off FOREIGN KEY (From_Officer_ID) REFERENCES Officers(Officer_ID),
    CONSTRAINT fk_ct_to_off   FOREIGN KEY (To_Officer_ID)   REFERENCES Officers(Officer_ID)
);

-- 7. Lab_Analysis
CREATE TABLE Lab_Analysis (
    Analysis_ID        NUMBER(6)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Evidence_ID        NUMBER(6)    NOT NULL,
    Lab_ID             NUMBER(6)    NOT NULL,
    Analyst_Officer_ID NUMBER(6)    NOT NULL,
    Start_Date         DATE         NOT NULL,
    End_Date           DATE,
    Findings           CLOB,
    Status             VARCHAR2(15) NOT NULL DEFAULT 'PENDING'
        CHECK (Status IN ('PENDING','IN_PROGRESS','COMPLETED')),
    CONSTRAINT fk_la_evidence FOREIGN KEY (Evidence_ID)        REFERENCES Evidence(Evidence_ID),
    CONSTRAINT fk_la_lab      FOREIGN KEY (Lab_ID)             REFERENCES Forensic_Labs(Lab_ID),
    CONSTRAINT fk_la_analyst  FOREIGN KEY (Analyst_Officer_ID) REFERENCES Officers(Officer_ID),
    CONSTRAINT chk_la_dates   CHECK (End_Date IS NULL OR End_Date >= Start_Date)
);

-- 8. Court_Requisitions
CREATE TABLE Court_Requisitions (
    Requisition_ID  NUMBER(6)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Evidence_ID     NUMBER(6)    NOT NULL,
    Case_ID         NUMBER(6)    NOT NULL,
    Court_Name      VARCHAR2(150) NOT NULL,
    Hearing_Date    DATE          NOT NULL,
    Requested_By_ID NUMBER(6)    NOT NULL,
    Status          VARCHAR2(15) NOT NULL DEFAULT 'PENDING'
        CHECK (Status IN ('PENDING','APPROVED','RETURNED','REJECTED')),
    Request_Date    DATE         NOT NULL DEFAULT SYSDATE,
    CONSTRAINT fk_cr_evidence FOREIGN KEY (Evidence_ID)     REFERENCES Evidence(Evidence_ID),
    CONSTRAINT fk_cr_case     FOREIGN KEY (Case_ID)         REFERENCES Cases(Case_ID),
    CONSTRAINT fk_cr_officer  FOREIGN KEY (Requested_By_ID) REFERENCES Officers(Officer_ID)
);

-- 9. Audit_Log
CREATE TABLE Audit_Log (
    Log_ID           NUMBER(10)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Table_Name       VARCHAR2(50) NOT NULL,
    Operation        VARCHAR2(10) NOT NULL
        CHECK (Operation IN ('INSERT','UPDATE','DELETE')),
    Record_ID        NUMBER(10)   NOT NULL,
    Officer_ID       NUMBER(6),
    Action_Timestamp TIMESTAMP    NOT NULL DEFAULT SYSTIMESTAMP,
    Old_Value        CLOB,
    New_Value        CLOB,
    IP_Note          VARCHAR2(200),
    CONSTRAINT fk_al_officer FOREIGN KEY (Officer_ID) REFERENCES Officers(Officer_ID)
);

-- Indexes
CREATE INDEX idx_ev_case     ON Evidence(Case_ID);
CREATE INDEX idx_ct_evidence ON Custody_Transfers(Evidence_ID);
CREATE INDEX idx_ct_date     ON Custody_Transfers(Transfer_Date);

-- ============================================================
-- SECTION 2: DML — SAMPLE DATA
-- ============================================================

-- Officers (6 rows)
INSERT INTO Officers (Name, Badge_Number, Rank, Department, Authorization_Level, Phone, Email)
VALUES ('Rajesh Kumar Sharma',  'DL-OFC-001', 'Sub-Inspector',    'Delhi Police - Crime Branch',       'OFFICER',    '9811001001', 'rkumar@dcp.gov.in');
INSERT INTO Officers (Name, Badge_Number, Rank, Department, Authorization_Level, Phone, Email)
VALUES ('Priya Nair',           'DL-ANA-002', 'Forensic Analyst', 'CFSL New Delhi',                    'ANALYST',    '9811002002', 'pnair@cfsl.gov.in');
INSERT INTO Officers (Name, Badge_Number, Rank, Department, Authorization_Level, Phone, Email)
VALUES ('Vikram Singh Rathore', 'DL-SUP-003', 'Inspector',        'Delhi Police - Homicide Division',  'SUPERVISOR', '9811003003', 'vsrathore@dcp.gov.in');
INSERT INTO Officers (Name, Badge_Number, Rank, Department, Authorization_Level, Phone, Email)
VALUES ('Anita Desai',          'MH-OFC-004', 'Constable',        'Mumbai Police - Evidence Cell',     'OFFICER',    '9822004004', 'adesai@mp.gov.in');
INSERT INTO Officers (Name, Badge_Number, Rank, Department, Authorization_Level, Phone, Email)
VALUES ('Mohammed Irfan',       'MH-ANA-005', 'Senior Analyst',   'FSL Mumbai',                        'ANALYST',    '9822005005', 'mirfan@fsl.gov.in');
INSERT INTO Officers (Name, Badge_Number, Rank, Department, Authorization_Level, Phone, Email)
VALUES ('Sunita Chauhan',       'DL-ADM-006', 'DCP',              'Delhi Police Headquarters',          'ADMIN',      '9811006006', 'schauhan@dcp.gov.in');

-- Forensic Labs (3 rows)
INSERT INTO Forensic_Labs (Lab_Name, Location, Specialization, Contact_Phone)
VALUES ('Central Forensic Science Laboratory', 'Lodhi Road, New Delhi',   'DNA, Toxicology, Digital Forensics', '01124360823');
INSERT INTO Forensic_Labs (Lab_Name, Location, Specialization, Contact_Phone)
VALUES ('Forensic Science Laboratory Mumbai',  'Santacruz East, Mumbai',  'Ballistics, Narcotics Analysis',     '02226149100');
INSERT INTO Forensic_Labs (Lab_Name, Location, Specialization, Contact_Phone)
VALUES ('Regional FSL Chandigarh',             'Sector 26, Chandigarh',   'Document Examination, Fingerprints', '01722640500');

-- Storage Facilities (3 rows)
INSERT INTO Storage_Facilities (Facility_Name, Location, Capacity, Facility_Type)
VALUES ('Delhi Police Malkhana - Central', 'Tis Hazari, New Delhi',    500, 'EVIDENCE_ROOM');
INSERT INTO Storage_Facilities (Facility_Name, Location, Capacity, Facility_Type)
VALUES ('CFSL Secure Bio-Storage Vault',   'Lodhi Road, New Delhi',     50, 'COLD_STORAGE');
INSERT INTO Storage_Facilities (Facility_Name, Location, Capacity, Facility_Type)
VALUES ('Cyber Crime Digital Evidence Vault', 'CGO Complex, New Delhi', 200, 'DIGITAL_VAULT');

-- Cases (5 rows)
INSERT INTO Cases (FIR_Number, Crime_Type, Date_Reported, Status, Investigating_Officer_ID, Description)
VALUES ('FIR/DL/2025/001', 'Murder',            DATE '2025-01-15', 'UNDER_INVESTIGATION', 3, 'Body found at Dwarka Sector 12. Suspected homicide.');
INSERT INTO Cases (FIR_Number, Crime_Type, Date_Reported, Status, Investigating_Officer_ID, Description)
VALUES ('FIR/DL/2025/002', 'Narcotics Seizure', DATE '2025-02-20', 'OPEN',               1, 'Large quantity of heroin seized at IGI Airport terminal.');
INSERT INTO Cases (FIR_Number, Crime_Type, Date_Reported, Status, Investigating_Officer_ID, Description)
VALUES ('FIR/MH/2025/003', 'Bank Fraud',        DATE '2025-03-05', 'OPEN',               3, 'Fraudulent transactions totalling Rs 2.4 crore at Andheri branch.');
INSERT INTO Cases (FIR_Number, Crime_Type, Date_Reported, Status, Investigating_Officer_ID, Description)
VALUES ('FIR/DL/2024/089', 'Robbery',           DATE '2024-11-10', 'CLOSED',             1, 'Armed robbery at jewellery shop in Karol Bagh. Case solved.');
INSERT INTO Cases (FIR_Number, Crime_Type, Date_Reported, Status, Investigating_Officer_ID, Description)
VALUES ('FIR/DL/2025/005', 'Cybercrime',        DATE '2025-04-01', 'UNDER_INVESTIGATION', 6, 'Ransomware attack on government portal. Digital forensics ongoing.');

-- Evidence (12 rows)
-- NOTE: trg_auto_first_custody fires AFTER each INSERT and auto-creates the initial custody record
INSERT INTO Evidence (Case_ID, Description, Category, Condition, Date_Collected, Current_Location, Current_Custodian_ID, Facility_ID, Tamper_Seal)
VALUES (1, 'Kitchen knife, 18cm blade, bloodstained',       'WEAPON',     'INTACT',  DATE '2025-01-15', 'Delhi Police Malkhana - Central',    1, 1, 'SEAL-EV-001');
INSERT INTO Evidence (Case_ID, Description, Category, Condition, Date_Collected, Current_Location, Current_Custodian_ID, Facility_ID, Tamper_Seal)
VALUES (1, 'Blood sample from crime scene - type AB+',      'BIOLOGICAL', 'INTACT',  DATE '2025-01-15', 'CFSL Bio-Storage Vault',             2, 2, 'SEAL-EV-002');
INSERT INTO Evidence (Case_ID, Description, Category, Condition, Date_Collected, Current_Location, Current_Custodian_ID, Facility_ID, Tamper_Seal)
VALUES (1, 'Victim mobile phone - Samsung Galaxy S23',      'ELECTRONIC', 'DAMAGED', DATE '2025-01-16', 'CFSL Digital Lab',                   2, 3, 'SEAL-EV-003');
INSERT INTO Evidence (Case_ID, Description, Category, Condition, Date_Collected, Current_Location, Current_Custodian_ID, Facility_ID, Tamper_Seal)
VALUES (2, 'Heroin 2.3kg in vacuum-sealed packets',         'NARCOTIC',   'INTACT',  DATE '2025-02-20', 'FSL Mumbai Narcotics Unit',          5, 1, 'SEAL-EV-004');
INSERT INTO Evidence (Case_ID, Description, Category, Condition, Date_Collected, Current_Location, Current_Custodian_ID, Facility_ID, Tamper_Seal)
VALUES (2, 'Forged customs clearance documents',            'DOCUMENT',   'INTACT',  DATE '2025-02-20', 'Delhi Police Malkhana - Central',    1, 1, 'SEAL-EV-005');
INSERT INTO Evidence (Case_ID, Description, Category, Condition, Date_Collected, Current_Location, Current_Custodian_ID, Facility_ID, Tamper_Seal)
VALUES (3, 'Laptop - Dell Latitude, suspect laptop',        'ELECTRONIC', 'INTACT',  DATE '2025-03-06', 'Cyber Crime Digital Evidence Vault', 6, 3, 'SEAL-EV-006');
INSERT INTO Evidence (Case_ID, Description, Category, Condition, Date_Collected, Current_Location, Current_Custodian_ID, Facility_ID, Tamper_Seal)
VALUES (3, 'Bank transaction printouts - 47 pages',         'DOCUMENT',   'INTACT',  DATE '2025-03-06', 'Delhi Police Malkhana - Central',    3, 1, 'SEAL-EV-007');
INSERT INTO Evidence (Case_ID, Description, Category, Condition, Date_Collected, Current_Location, Current_Custodian_ID, Facility_ID, Tamper_Seal)
VALUES (4, 'Revolver - .32 calibre, 3 rounds fired',        'WEAPON',     'INTACT',  DATE '2024-11-10', 'Delhi Police Malkhana - Central',    3, 1, 'SEAL-EV-008');
INSERT INTO Evidence (Case_ID, Description, Category, Condition, Date_Collected, Current_Location, Current_Custodian_ID, Facility_ID, Tamper_Seal)
VALUES (4, 'CCTV footage from shop - USB drive',            'ELECTRONIC', 'INTACT',  DATE '2024-11-10', 'Delhi Police Malkhana - Central',    3, 1, 'SEAL-EV-009');
INSERT INTO Evidence (Case_ID, Description, Category, Condition, Date_Collected, Current_Location, Current_Custodian_ID, Facility_ID, Tamper_Seal)
VALUES (5, 'Infected USB drive used in ransomware attack',  'ELECTRONIC', 'INTACT',  DATE '2025-04-02', 'Cyber Crime Digital Evidence Vault', 6, 3, 'SEAL-EV-010');
INSERT INTO Evidence (Case_ID, Description, Category, Condition, Date_Collected, Current_Location, Current_Custodian_ID, Facility_ID, Tamper_Seal)
VALUES (5, 'Server access logs - printed 200 pages',        'DOCUMENT',   'INTACT',  DATE '2025-04-02', 'CGO Complex, New Delhi',             6, NULL, 'SEAL-EV-011');
INSERT INTO Evidence (Case_ID, Description, Category, Condition, Date_Collected, Current_Location, Current_Custodian_ID, Facility_ID, Tamper_Seal)
VALUES (1, 'Fingerprints lifted from door handle - 3 sets', 'OTHER',      'INTACT',  DATE '2025-01-15', 'CFSL New Delhi',                     2, NULL, 'SEAL-EV-012');

-- Additional Custody_Transfers (beyond auto-created initial ones)
INSERT INTO Custody_Transfers (Evidence_ID, From_Officer_ID, To_Officer_ID, Transfer_Date, Location, Reason, Evidence_Condition, Status, Is_Sealed)
VALUES (1, 1, 3, DATE '2025-01-16', 'Delhi Police HQ',  'Transfer to supervising officer for case review',  'INTACT', 'COMPLETED', 'Y');
INSERT INTO Custody_Transfers (Evidence_ID, From_Officer_ID, To_Officer_ID, Transfer_Date, Location, Reason, Evidence_Condition, Status, Is_Sealed)
VALUES (1, 3, 2, DATE '2025-01-18', 'CFSL New Delhi',   'Sent to forensic lab for DNA analysis on blade',   'INTACT', 'COMPLETED', 'Y');
INSERT INTO Custody_Transfers (Evidence_ID, From_Officer_ID, To_Officer_ID, Transfer_Date, Location, Reason, Evidence_Condition, Status, Is_Sealed)
VALUES (2, 1, 2, DATE '2025-01-15', 'Crime Scene - Dwarka', 'Immediate transfer to forensic analyst',       'INTACT', 'COMPLETED', 'Y');
INSERT INTO Custody_Transfers (Evidence_ID, From_Officer_ID, To_Officer_ID, Transfer_Date, Location, Reason, Evidence_Condition, Status, Is_Sealed)
VALUES (2, 2, 2, DATE '2025-01-20', 'CFSL New Delhi',   'Re-catalogued after preliminary DNA typing',       'INTACT', 'COMPLETED', 'Y');
INSERT INTO Custody_Transfers (Evidence_ID, From_Officer_ID, To_Officer_ID, Transfer_Date, Location, Reason, Evidence_Condition, Status, Is_Sealed)
VALUES (4, 1, 5, DATE '2025-02-21', 'IGI Airport Police Post', 'Transfer to FSL Mumbai for chemical analysis', 'INTACT', 'COMPLETED', 'Y');
INSERT INTO Custody_Transfers (Evidence_ID, From_Officer_ID, To_Officer_ID, Transfer_Date, Location, Reason, Evidence_Condition, Status, Is_Sealed)
VALUES (8, 1, 3, DATE '2024-11-11', 'Delhi Police HQ',  'Transfer for ballistics examination',              'INTACT', 'COMPLETED', 'Y');
INSERT INTO Custody_Transfers (Evidence_ID, From_Officer_ID, To_Officer_ID, Transfer_Date, Location, Reason, Evidence_Condition, Status, Is_Sealed)
VALUES (8, 3, 1, DATE '2024-11-25', 'Delhi Police Malkhana', 'Returned after ballistics report',            'INTACT', 'COMPLETED', 'Y');
-- One overdue PENDING transfer for query demo
INSERT INTO Custody_Transfers (Evidence_ID, From_Officer_ID, To_Officer_ID, Transfer_Date, Location, Reason, Evidence_Condition, Status, Is_Sealed)
VALUES (6, 6, 5, DATE '2025-03-08', 'Cyber Crime Unit, Delhi', 'Sent to FSL for digital forensics analysis', 'INTACT', 'PENDING', 'N');

-- Lab_Analysis (5 rows)
INSERT INTO Lab_Analysis (Evidence_ID, Lab_ID, Analyst_Officer_ID, Start_Date, End_Date, Findings, Status)
VALUES (1, 1, 2, DATE '2025-01-19', DATE '2025-01-30',
        'DNA profile extracted from blade. Match with victim 99.7% confidence. Fingerprints of unknown subject detected.', 'COMPLETED');
INSERT INTO Lab_Analysis (Evidence_ID, Lab_ID, Analyst_Officer_ID, Start_Date, End_Date, Findings, Status)
VALUES (2, 1, 2, DATE '2025-01-19', NULL, 'Blood sample categorised AB+. DNA extraction in progress.', 'IN_PROGRESS');
INSERT INTO Lab_Analysis (Evidence_ID, Lab_ID, Analyst_Officer_ID, Start_Date, End_Date, Findings, Status)
VALUES (4, 2, 5, DATE '2025-02-22', DATE '2025-03-05',
        'Substance confirmed as diacetylmorphine (heroin), purity 84.2%. Weight 2.287kg net.', 'COMPLETED');
INSERT INTO Lab_Analysis (Evidence_ID, Lab_ID, Analyst_Officer_ID, Start_Date, End_Date, Findings, Status)
VALUES (8, 1, 2, DATE '2024-11-12', DATE '2024-11-20',
        'Revolver identified as .32 bore SBML. Three rounds fired. Ballistics match to spent cartridges at scene.', 'COMPLETED');
INSERT INTO Lab_Analysis (Evidence_ID, Lab_ID, Analyst_Officer_ID, Start_Date, End_Date, Findings, Status)
VALUES (6, 3, 2, DATE '2025-04-05', NULL, NULL, 'PENDING');

-- Court_Requisitions (4 rows)
INSERT INTO Court_Requisitions (Evidence_ID, Case_ID, Court_Name, Hearing_Date, Requested_By_ID, Status, Request_Date)
VALUES (1, 1, 'Sessions Court Delhi - Court No. 7',             DATE '2025-06-15', 3, 'APPROVED', DATE '2025-05-01');
INSERT INTO Court_Requisitions (Evidence_ID, Case_ID, Court_Name, Hearing_Date, Requested_By_ID, Status, Request_Date)
VALUES (2, 1, 'Sessions Court Delhi - Court No. 7',             DATE '2025-06-15', 3, 'PENDING',  DATE '2025-05-01');
INSERT INTO Court_Requisitions (Evidence_ID, Case_ID, Court_Name, Hearing_Date, Requested_By_ID, Status, Request_Date)
VALUES (8, 4, 'Additional Sessions Court Delhi - Court No. 12', DATE '2025-02-10', 1, 'RETURNED', DATE '2025-01-20');
INSERT INTO Court_Requisitions (Evidence_ID, Case_ID, Court_Name, Hearing_Date, Requested_By_ID, Status, Request_Date)
VALUES (4, 2, 'Special NDPS Court Mumbai',                      DATE '2025-07-20', 5, 'PENDING',  DATE '2025-05-10');

COMMIT;

-- ============================================================
-- SECTION 3: COMPLEX SQL QUERIES
-- ============================================================

-- Query 1: Complete custody chain for Evidence ID 1 (3-table join)
SELECT
    e.Evidence_ID, e.Description AS Evidence_Description, e.Tamper_Seal,
    ct.Transfer_ID, ct.Transfer_Date,
    f.Name AS From_Officer, f.Badge_Number AS From_Badge,
    t.Name AS To_Officer,   t.Badge_Number AS To_Badge,
    ct.Location, ct.Reason, ct.Status AS Transfer_Status, ct.Is_Sealed
FROM Evidence e
JOIN Custody_Transfers ct ON e.Evidence_ID     = ct.Evidence_ID
JOIN Officers f           ON ct.From_Officer_ID = f.Officer_ID
JOIN Officers t           ON ct.To_Officer_ID   = t.Officer_ID
WHERE e.Evidence_ID = 1
ORDER BY ct.Transfer_Date ASC;

-- Query 2: All evidence for Case 1 with current custodian details (3-table join)
SELECT
    c.FIR_Number, c.Crime_Type,
    e.Evidence_ID, e.Description, e.Category, e.Condition, e.Tamper_Seal,
    o.Name AS Current_Custodian, o.Badge_Number, o.Department, e.Current_Location
FROM Cases c
JOIN Evidence e ON c.Case_ID              = e.Case_ID
JOIN Officers o ON e.Current_Custodian_ID = o.Officer_ID
WHERE c.Case_ID = 1
ORDER BY e.Evidence_ID;

-- Query 3: Evidence that has never been transferred out (correlated subquery)
SELECT
    e.Evidence_ID, e.Description, e.Category, e.Date_Collected, e.Tamper_Seal,
    o.Name AS Initial_Custodian
FROM Evidence e
JOIN Officers o ON e.Current_Custodian_ID = o.Officer_ID
WHERE NOT EXISTS (
    SELECT 1 FROM Custody_Transfers ct
    WHERE ct.Evidence_ID = e.Evidence_ID
      AND ct.Reason <> 'INITIAL_COLLECTION'
);

-- Query 4: Officers who have handled evidence from more than 2 different cases (correlated subquery)
SELECT
    o.Officer_ID, o.Name, o.Badge_Number, o.Rank, o.Department,
    (SELECT COUNT(DISTINCT e2.Case_ID)
     FROM Custody_Transfers ct2
     JOIN Evidence e2 ON ct2.Evidence_ID = e2.Evidence_ID
     WHERE ct2.From_Officer_ID = o.Officer_ID
        OR ct2.To_Officer_ID   = o.Officer_ID) AS Cases_Handled
FROM Officers o
WHERE (
    SELECT COUNT(DISTINCT e.Case_ID)
    FROM Custody_Transfers ct
    JOIN Evidence e ON ct.Evidence_ID = e.Evidence_ID
    WHERE ct.From_Officer_ID = o.Officer_ID
       OR ct.To_Officer_ID   = o.Officer_ID
) > 2
ORDER BY Cases_Handled DESC;

-- Query 5: Evidence count per case + average lab analysis duration (GROUP BY + aggregate)
SELECT
    c.Case_ID, c.FIR_Number, c.Crime_Type, c.Status,
    COUNT(DISTINCT e.Evidence_ID)              AS Evidence_Count,
    ROUND(AVG(la.End_Date - la.Start_Date), 1) AS Avg_Analysis_Days,
    COUNT(DISTINCT la.Analysis_ID)             AS Total_Analyses
FROM Cases c
LEFT JOIN Evidence e     ON c.Case_ID     = e.Case_ID
LEFT JOIN Lab_Analysis la ON e.Evidence_ID = la.Evidence_ID AND la.Status = 'COMPLETED'
GROUP BY c.Case_ID, c.FIR_Number, c.Crime_Type, c.Status
ORDER BY Evidence_Count DESC;

-- Query 6: Crime types with more than 2 evidence items (GROUP BY + HAVING)
SELECT
    c.Crime_Type,
    COUNT(e.Evidence_ID)      AS Total_Evidence,
    COUNT(DISTINCT c.Case_ID) AS Num_Cases
FROM Cases c
JOIN Evidence e ON c.Case_ID = e.Case_ID
GROUP BY c.Crime_Type
HAVING COUNT(e.Evidence_ID) > 2
ORDER BY Total_Evidence DESC;

-- Query 7: Departments ranked by transfer activity (aggregate)
SELECT
    o.Department,
    COUNT(DISTINCT o.Officer_ID)   AS Officers_In_Dept,
    COUNT(ct.Transfer_ID)          AS Total_Transfers_Handled,
    COUNT(DISTINCT ct.Evidence_ID) AS Distinct_Evidence_Handled
FROM Officers o
LEFT JOIN (
    SELECT From_Officer_ID AS Officer_ID, Transfer_ID, Evidence_ID FROM Custody_Transfers
    UNION ALL
    SELECT To_Officer_ID,                 Transfer_ID, Evidence_ID FROM Custody_Transfers
) ct ON o.Officer_ID = ct.Officer_ID
GROUP BY o.Department
ORDER BY Total_Transfers_Handled DESC;

-- Query 8: Evidence overdue in transit — PENDING transfers older than 2 days
SELECT
    e.Evidence_ID, e.Description, e.Tamper_Seal,
    c.FIR_Number, c.Crime_Type,
    ct.Transfer_ID, ct.Transfer_Date,
    ROUND(SYSDATE - ct.Transfer_Date) AS Days_Overdue,
    f.Name AS From_Officer, t.Name AS Assigned_To, t.Phone AS Assignee_Phone,
    ct.Location AS Last_Known_Location
FROM Custody_Transfers ct
JOIN Evidence e  ON ct.Evidence_ID     = e.Evidence_ID
JOIN Cases c     ON e.Case_ID          = c.Case_ID
JOIN Officers f  ON ct.From_Officer_ID = f.Officer_ID
JOIN Officers t  ON ct.To_Officer_ID   = t.Officer_ID
WHERE ct.Status = 'PENDING'
  AND ct.Transfer_Date < SYSDATE - 2
ORDER BY Days_Overdue DESC;

-- ============================================================
-- SECTION 4: VIEWS
-- (No ORDER BY inside view definitions -- Oracle does not permit it)
-- ============================================================

CREATE OR REPLACE VIEW v_active_cases AS
SELECT
    c.Case_ID, c.FIR_Number, c.Crime_Type, c.Date_Reported, c.Status,
    o.Name AS Investigating_Officer, o.Badge_Number,
    COUNT(e.Evidence_ID) AS Evidence_Count
FROM Cases c
JOIN Officers o   ON c.Investigating_Officer_ID = o.Officer_ID
LEFT JOIN Evidence e ON c.Case_ID = e.Case_ID
WHERE c.Status IN ('OPEN','UNDER_INVESTIGATION')
GROUP BY c.Case_ID, c.FIR_Number, c.Crime_Type, c.Date_Reported, c.Status,
         o.Name, o.Badge_Number;

CREATE OR REPLACE VIEW v_custody_chain AS
SELECT
    e.Evidence_ID, e.Description AS Evidence_Description, e.Tamper_Seal,
    c.FIR_Number, c.Crime_Type,
    ct.Transfer_ID, ct.Transfer_Date,
    f.Name AS From_Officer, t.Name AS To_Officer,
    ct.Location, ct.Reason, ct.Evidence_Condition,
    ct.Status AS Transfer_Status, ct.Is_Sealed
FROM Evidence e
JOIN Cases c              ON e.Case_ID           = c.Case_ID
JOIN Custody_Transfers ct ON e.Evidence_ID       = ct.Evidence_ID
JOIN Officers f           ON ct.From_Officer_ID  = f.Officer_ID
JOIN Officers t           ON ct.To_Officer_ID    = t.Officer_ID;

CREATE OR REPLACE VIEW v_lab_pending AS
SELECT
    e.Evidence_ID, e.Description AS Evidence_Description, e.Category, e.Tamper_Seal,
    c.FIR_Number, fl.Lab_Name, fl.Location AS Lab_Location,
    la.Analysis_ID, la.Start_Date, la.End_Date,
    ROUND(SYSDATE - la.Start_Date) AS Days_In_Lab,
    la.Status AS Analysis_Status, o.Name AS Analyst
FROM Lab_Analysis la
JOIN Evidence e     ON la.Evidence_ID        = e.Evidence_ID
JOIN Cases c        ON e.Case_ID             = c.Case_ID
JOIN Forensic_Labs fl ON la.Lab_ID           = fl.Lab_ID
JOIN Officers o     ON la.Analyst_Officer_ID = o.Officer_ID
WHERE la.Status IN ('PENDING','IN_PROGRESS');

CREATE OR REPLACE VIEW v_court_schedule AS
SELECT
    cr.Requisition_ID, cr.Hearing_Date, cr.Court_Name,
    cr.Status AS Requisition_Status,
    c.FIR_Number, c.Crime_Type,
    e.Evidence_ID, e.Description AS Evidence_Description,
    e.Tamper_Seal, e.Condition AS Evidence_Condition,
    o.Name AS Requested_By, o.Badge_Number, cr.Request_Date
FROM Court_Requisitions cr
JOIN Evidence e ON cr.Evidence_ID     = e.Evidence_ID
JOIN Cases c    ON cr.Case_ID         = c.Case_ID
JOIN Officers o ON cr.Requested_By_ID = o.Officer_ID
WHERE cr.Hearing_Date >= SYSDATE - 30;

-- ============================================================
-- SECTION 5a: BYPASS PACKAGE
-- ============================================================

CREATE OR REPLACE PACKAGE pkg_bypass AS
    g_in_procedure BOOLEAN := FALSE;
END pkg_bypass;
/

-- ============================================================
-- SECTION 5b: TRIGGERS
-- ============================================================

CREATE OR REPLACE TRIGGER trg_auto_first_custody
AFTER INSERT ON Evidence
FOR EACH ROW
BEGIN
    INSERT INTO Custody_Transfers (
        Evidence_ID, From_Officer_ID, To_Officer_ID,
        Transfer_Date, Location, Reason,
        Evidence_Condition, Status, Is_Sealed
    ) VALUES (
        :NEW.Evidence_ID,
        :NEW.Current_Custodian_ID, :NEW.Current_Custodian_ID,
        :NEW.Date_Collected, :NEW.Current_Location, 'INITIAL_COLLECTION',
        :NEW.Condition, 'COMPLETED', 'Y'
    );
END;
/

CREATE OR REPLACE TRIGGER trg_tamper_lock
BEFORE UPDATE OR DELETE ON Custody_Transfers
FOR EACH ROW
BEGIN
    IF :OLD.Is_Sealed = 'Y' AND NOT pkg_bypass.g_in_procedure THEN
        INSERT INTO Audit_Log (
            Table_Name, Operation, Record_ID, Officer_ID, Action_Timestamp, IP_Note
        ) VALUES (
            'CUSTODY_TRANSFERS',
            CASE WHEN DELETING THEN 'DELETE' ELSE 'UPDATE' END,
            :OLD.Transfer_ID, NULL, SYSTIMESTAMP,
            'TAMPER ATTEMPT on Transfer_ID=' || :OLD.Transfer_ID
        );
        RAISE_APPLICATION_ERROR(-20001,
            'CHAINGUARD SECURITY: Cannot modify sealed custody record (Transfer_ID=' ||
            :OLD.Transfer_ID || '). Chain of custody is immutable once sealed.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_evidence_audit
AFTER INSERT OR UPDATE OR DELETE ON Evidence
FOR EACH ROW
DECLARE
    v_op      VARCHAR2(10);
    v_old_val VARCHAR2(500);
    v_new_val VARCHAR2(500);
    v_rec_id  NUMBER;
    v_off_id  NUMBER;
BEGIN
    IF INSERTING THEN
        v_op := 'INSERT'; v_rec_id := :NEW.Evidence_ID; v_off_id := :NEW.Current_Custodian_ID;
        v_old_val := NULL;
        v_new_val := 'EV_ID=' || :NEW.Evidence_ID || '|Case=' || :NEW.Case_ID ||
                     '|Cat=' || :NEW.Category || '|Cust=' || :NEW.Current_Custodian_ID ||
                     '|Seal=' || :NEW.Tamper_Seal;
    ELSIF UPDATING THEN
        v_op := 'UPDATE'; v_rec_id := :NEW.Evidence_ID; v_off_id := :NEW.Current_Custodian_ID;
        v_old_val := 'Cust=' || :OLD.Current_Custodian_ID || '|Loc=' || :OLD.Current_Location || '|Cond=' || :OLD.Condition;
        v_new_val := 'Cust=' || :NEW.Current_Custodian_ID || '|Loc=' || :NEW.Current_Location || '|Cond=' || :NEW.Condition;
    ELSE
        v_op := 'DELETE'; v_rec_id := :OLD.Evidence_ID; v_off_id := :OLD.Current_Custodian_ID;
        v_old_val := 'EV_ID=' || :OLD.Evidence_ID || '|Seal=' || :OLD.Tamper_Seal;
        v_new_val := NULL;
    END IF;
    INSERT INTO Audit_Log (Table_Name, Operation, Record_ID, Officer_ID, Action_Timestamp, Old_Value, New_Value)
    VALUES ('EVIDENCE', v_op, v_rec_id, v_off_id, SYSTIMESTAMP, v_old_val, v_new_val);
END;
/

-- ============================================================
-- SECTION 5c: STORED PROCEDURE -- sp_custody_transfer
-- ============================================================

CREATE OR REPLACE PROCEDURE sp_custody_transfer (
    p_evidence_id     IN NUMBER,
    p_from_officer_id IN NUMBER,
    p_to_officer_id   IN NUMBER,
    p_location        IN VARCHAR2,
    p_reason          IN VARCHAR2,
    p_condition       IN VARCHAR2
)
AS
    v_current_custodian NUMBER;
    v_to_auth_level     VARCHAR2(20);
    v_old_transfer_id   NUMBER;
    e_wrong_custodian EXCEPTION;
    e_unauth_officer  EXCEPTION;
BEGIN
    SAVEPOINT sp_transfer_start;

    SELECT Current_Custodian_ID INTO v_current_custodian
    FROM   Evidence WHERE Evidence_ID = p_evidence_id FOR UPDATE;

    IF v_current_custodian <> p_from_officer_id THEN RAISE e_wrong_custodian; END IF;

    SELECT Authorization_Level INTO v_to_auth_level
    FROM   Officers WHERE Officer_ID = p_to_officer_id;

    IF v_to_auth_level = 'OFFICER' AND UPPER(p_reason) LIKE '%LAB%' THEN RAISE e_unauth_officer; END IF;

    SAVEPOINT sp_before_update;

    BEGIN
        SELECT Transfer_ID INTO v_old_transfer_id
        FROM (
            SELECT Transfer_ID FROM Custody_Transfers
            WHERE  Evidence_ID = p_evidence_id AND Status = 'PENDING'
            ORDER  BY Transfer_Date DESC, Transfer_ID DESC
        ) WHERE ROWNUM = 1;

        pkg_bypass.g_in_procedure := TRUE;
        UPDATE Custody_Transfers SET Status='COMPLETED', Is_Sealed='Y' WHERE Transfer_ID = v_old_transfer_id;
        pkg_bypass.g_in_procedure := FALSE;
    EXCEPTION WHEN NO_DATA_FOUND THEN NULL;
    END;

    INSERT INTO Custody_Transfers (
        Evidence_ID, From_Officer_ID, To_Officer_ID,
        Transfer_Date, Location, Reason, Evidence_Condition, Status, Is_Sealed
    ) VALUES (
        p_evidence_id, p_from_officer_id, p_to_officer_id,
        SYSDATE, p_location, p_reason, p_condition, 'PENDING', 'N'
    );

    UPDATE Evidence
    SET Current_Custodian_ID = p_to_officer_id, Current_Location = p_location, Condition = p_condition
    WHERE Evidence_ID = p_evidence_id;

    COMMIT;
    pkg_bypass.g_in_procedure := FALSE;
    DBMS_OUTPUT.PUT_LINE('SUCCESS: Evidence ' || p_evidence_id || ' transferred to Officer ' || p_to_officer_id);

EXCEPTION
    WHEN e_wrong_custodian THEN
        ROLLBACK TO sp_transfer_start; pkg_bypass.g_in_procedure := FALSE;
        RAISE_APPLICATION_ERROR(-20002, 'Transfer failed: Officer ' || p_from_officer_id || ' is not the current custodian.');
    WHEN e_unauth_officer THEN
        ROLLBACK TO sp_transfer_start; pkg_bypass.g_in_procedure := FALSE;
        RAISE_APPLICATION_ERROR(-20003, 'Transfer failed: Officer ' || p_to_officer_id || ' lacks authorization.');
    WHEN OTHERS THEN
        ROLLBACK TO sp_transfer_start; pkg_bypass.g_in_procedure := FALSE; RAISE;
END sp_custody_transfer;
/

-- ============================================================
-- SECTION 5d: STORED FUNCTION -- fn_validate_chain_integrity
-- ============================================================

CREATE OR REPLACE FUNCTION fn_validate_chain_integrity (
    p_evidence_id IN NUMBER
) RETURN VARCHAR2
AS
    CURSOR c_chain IS
        SELECT Transfer_ID, From_Officer_ID, To_Officer_ID, Transfer_Date
        FROM   Custody_Transfers
        WHERE  Evidence_ID = p_evidence_id
        ORDER  BY Transfer_Date ASC, Transfer_ID ASC;

    v_prev_to NUMBER  := NULL;
    v_prev_dt DATE    := NULL;
    v_first   BOOLEAN := TRUE;
    v_count   NUMBER  := 0;
BEGIN
    FOR r IN c_chain LOOP
        v_count := v_count + 1;
        IF v_first THEN
            IF r.From_Officer_ID <> r.To_Officer_ID THEN
                RETURN 'BROKEN: First record (Transfer_ID=' || r.Transfer_ID || ') is not INITIAL_COLLECTION.';
            END IF;
            v_first := FALSE;
        ELSE
            IF v_prev_to <> r.From_Officer_ID THEN
                RETURN 'BROKEN: Gap at Transfer_ID=' || r.Transfer_ID ||
                       '. Expected From_Officer=' || v_prev_to || ' got ' || r.From_Officer_ID || '.';
            END IF;
            IF (r.Transfer_Date - v_prev_dt) > 30 THEN
                RETURN 'BROKEN: Time gap of ' || ROUND(r.Transfer_Date - v_prev_dt) ||
                       ' days before Transfer_ID=' || r.Transfer_ID || '.';
            END IF;
        END IF;
        v_prev_to := r.To_Officer_ID;
        v_prev_dt := r.Transfer_Date;
    END LOOP;

    IF v_count = 0 THEN RETURN 'BROKEN: No custody records found for Evidence_ID=' || p_evidence_id; END IF;
    RETURN 'INTACT';
END fn_validate_chain_integrity;
/

-- ============================================================
-- SECTION 5e: PL/SQL PACKAGE -- pkg_chainguard_reports
-- ============================================================

CREATE OR REPLACE PACKAGE pkg_chainguard_reports AS
    PROCEDURE generate_case_report (p_case_id IN NUMBER);
    PROCEDURE flag_overdue_evidence;
END pkg_chainguard_reports;
/

CREATE OR REPLACE PACKAGE BODY pkg_chainguard_reports AS

    PROCEDURE generate_case_report (p_case_id IN NUMBER) AS
        CURSOR c_ev IS
            SELECT Evidence_ID, Description, Category, Tamper_Seal, Condition
            FROM Evidence WHERE Case_ID = p_case_id ORDER BY Evidence_ID;
        CURSOR c_tr (p_ev NUMBER) IS
            SELECT ct.Transfer_Date, f.Name AS From_Off, t.Name AS To_Off,
                   ct.Location, ct.Reason, ct.Status, ct.Is_Sealed
            FROM Custody_Transfers ct
            JOIN Officers f ON ct.From_Officer_ID = f.Officer_ID
            JOIN Officers t ON ct.To_Officer_ID   = t.Officer_ID
            WHERE ct.Evidence_ID = p_ev
            ORDER BY ct.Transfer_Date ASC, ct.Transfer_ID ASC;
        v_fir VARCHAR2(30);
    BEGIN
        SELECT FIR_Number INTO v_fir FROM Cases WHERE Case_ID = p_case_id;
        DBMS_OUTPUT.PUT_LINE('================================================');
        DBMS_OUTPUT.PUT_LINE('CHAINGUARD CUSTODY CHAIN REPORT');
        DBMS_OUTPUT.PUT_LINE('Case: ' || p_case_id || ' | FIR: ' || v_fir);
        DBMS_OUTPUT.PUT_LINE('Generated: ' || TO_CHAR(SYSDATE,'DD-MON-YYYY HH24:MI:SS'));
        DBMS_OUTPUT.PUT_LINE('================================================');
        FOR ev IN c_ev LOOP
            DBMS_OUTPUT.PUT_LINE('');
            DBMS_OUTPUT.PUT_LINE('EVIDENCE #' || ev.Evidence_ID || ' [' || ev.Category || '] ' || ev.Description);
            DBMS_OUTPUT.PUT_LINE('  Seal  : ' || ev.Tamper_Seal);
            DBMS_OUTPUT.PUT_LINE('  Chain : ' || fn_validate_chain_integrity(ev.Evidence_ID));
            FOR tr IN c_tr(ev.Evidence_ID) LOOP
                DBMS_OUTPUT.PUT_LINE('    ' || TO_CHAR(tr.Transfer_Date,'DD-MON-YYYY') ||
                    ' | ' || tr.From_Off || ' -> ' || tr.To_Off ||
                    ' | ' || tr.Reason || ' | ' || tr.Status ||
                    CASE WHEN tr.Is_Sealed='Y' THEN ' [SEALED]' ELSE '' END);
            END LOOP;
        END LOOP;
        DBMS_OUTPUT.PUT_LINE('');
        DBMS_OUTPUT.PUT_LINE('=== END OF REPORT ===');
    EXCEPTION WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: Case ID ' || p_case_id || ' not found.');
    END generate_case_report;

    PROCEDURE flag_overdue_evidence AS
        CURSOR c_ov IS
            SELECT e.Evidence_ID, e.Description, e.Tamper_Seal,
                   c.FIR_Number, c.Crime_Type,
                   ct.Transfer_ID, ct.Transfer_Date,
                   ROUND(SYSDATE - ct.Transfer_Date) AS Days_Overdue,
                   f.Name AS From_Officer, t.Name AS Assigned_To, t.Phone
            FROM Custody_Transfers ct
            JOIN Evidence e ON ct.Evidence_ID     = e.Evidence_ID
            JOIN Cases c    ON e.Case_ID          = c.Case_ID
            JOIN Officers f ON ct.From_Officer_ID = f.Officer_ID
            JOIN Officers t ON ct.To_Officer_ID   = t.Officer_ID
            WHERE ct.Status = 'PENDING' AND ct.Transfer_Date < SYSDATE - 2
            ORDER BY Days_Overdue DESC;
        v_n NUMBER := 0;
    BEGIN
        DBMS_OUTPUT.PUT_LINE('================================================');
        DBMS_OUTPUT.PUT_LINE('CHAINGUARD OVERDUE EVIDENCE ALERT');
        DBMS_OUTPUT.PUT_LINE('Run: ' || TO_CHAR(SYSDATE,'DD-MON-YYYY HH24:MI:SS'));
        DBMS_OUTPUT.PUT_LINE('================================================');
        FOR r IN c_ov LOOP
            v_n := v_n + 1;
            DBMS_OUTPUT.PUT_LINE('ALERT #' || v_n || ': ' || r.Evidence_ID || ' - ' || r.Description);
            DBMS_OUTPUT.PUT_LINE('  FIR     : ' || r.FIR_Number || ' (' || r.Crime_Type || ')');
            DBMS_OUTPUT.PUT_LINE('  Overdue : ' || r.Days_Overdue || ' day(s) since ' || TO_CHAR(r.Transfer_Date,'DD-MON-YYYY'));
            DBMS_OUTPUT.PUT_LINE('  Assigned: ' || r.Assigned_To || ' | ' || r.Phone);
        END LOOP;
        IF v_n = 0 THEN DBMS_OUTPUT.PUT_LINE('No overdue transfers found.');
        ELSE DBMS_OUTPUT.PUT_LINE('TOTAL OVERDUE: ' || v_n); END IF;
        DBMS_OUTPUT.PUT_LINE('================================================');
    END flag_overdue_evidence;

END pkg_chainguard_reports;
/

-- ============================================================
-- SECTION 6: TRANSACTION MANAGEMENT DEMONSTRATION
-- ============================================================

DECLARE
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== TRANSACTION DEMO ===');

    -- TEST 1: Wrong releasing officer -> ROLLBACK
    DBMS_OUTPUT.PUT_LINE('TEST 1: Wrong releasing officer');
    BEGIN
        SAVEPOINT sp_test1;
        sp_custody_transfer(3, 4, 5, 'FSL Mumbai', 'Transfer for analysis', 'DAMAGED');
    EXCEPTION WHEN OTHERS THEN
        ROLLBACK TO sp_test1;
        DBMS_OUTPUT.PUT_LINE('  RESULT: Rolled back. ' || SQLERRM);
    END;

    -- TEST 2: Valid transfer -> COMMIT
    DBMS_OUTPUT.PUT_LINE('TEST 2: Valid transfer (Officer 2 -> Officer 5 for Evidence 3)');
    BEGIN
        SAVEPOINT sp_test2;
        sp_custody_transfer(3, 2, 5, 'FSL Mumbai - Digital Forensics Unit',
                            'Sent for data extraction and mobile forensics', 'DAMAGED');
        DBMS_OUTPUT.PUT_LINE('  RESULT: Committed successfully.');
    EXCEPTION WHEN OTHERS THEN
        ROLLBACK TO sp_test2;
        DBMS_OUTPUT.PUT_LINE('  RESULT: Error - ' || SQLERRM);
    END;

    -- TEST 3: Chain integrity validation
    DBMS_OUTPUT.PUT_LINE('TEST 3: Chain integrity');
    DBMS_OUTPUT.PUT_LINE('  Evidence 1: ' || fn_validate_chain_integrity(1));
    DBMS_OUTPUT.PUT_LINE('  Evidence 3: ' || fn_validate_chain_integrity(3));

    -- TEST 4: Tamper detection
    DBMS_OUTPUT.PUT_LINE('TEST 4: Tamper attempt on sealed Transfer_ID=1');
    BEGIN
        UPDATE Custody_Transfers SET Reason='TAMPERED' WHERE Transfer_ID=1;
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('  RESULT: ERROR -- tamper block did not fire!');
    EXCEPTION WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('  RESULT: Blocked. ' || SQLERRM);
    END;

    DBMS_OUTPUT.PUT_LINE('=== DEMO COMPLETE ===');
END;
/

-- ============================================================
-- SECTION 7: VERIFICATION QUERIES
-- ============================================================

SELECT * FROM v_active_cases ORDER BY Date_Reported DESC;

SELECT Evidence_ID, Evidence_Description, Tamper_Seal, Transfer_Date,
       From_Officer, To_Officer, Reason, Transfer_Status
FROM v_custody_chain ORDER BY Evidence_ID, Transfer_Date;

SELECT * FROM v_lab_pending;

SELECT * FROM v_court_schedule ORDER BY Hearing_Date;

SELECT Log_ID, Table_Name, Operation, Record_ID,
       TO_CHAR(Action_Timestamp,'DD-MON-YYYY HH24:MI:SS') AS Log_Time,
       SUBSTR(New_Value,1,80) AS New_Val, IP_Note
FROM Audit_Log ORDER BY Log_ID DESC
FETCH FIRST 20 ROWS ONLY;

BEGIN pkg_chainguard_reports.generate_case_report(1); END;
/

BEGIN pkg_chainguard_reports.flag_overdue_evidence; END;
/

SELECT e.Evidence_ID, e.Description, e.Tamper_Seal,
       fn_validate_chain_integrity(e.Evidence_ID) AS Chain_Status
FROM Evidence e ORDER BY e.Evidence_ID;

-- ============================================================
-- END OF CHAINGUARD COMPLETE SQL SCRIPT
-- ============================================================
